package io.github.itsmelissadev.swiftsense.ui.theme

import androidx.compose.ui.graphics.Color

val SeedPrimary = Color(0xFFFF00FF)

val LightPrimary = Color(0xFFAC00AC)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFD7F3)
val LightOnPrimaryContainer = Color(0xFF390039)
val LightSecondary = Color(0xFF6F576A)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFF9DAEF)
val LightOnSecondaryContainer = Color(0xFF271525)
val LightTertiary = Color(0xFF825249)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDAD4)
val LightOnTertiaryContainer = Color(0xFF33110B)
val LightBackground = Color(0xFFFFFBFF)
val LightOnBackground = Color(0xFF1E1A1D)
val LightSurface = Color(0xFFFFFBFF)
val LightOnSurface = Color(0xFF1E1A1D)
val LightSurfaceVariant = Color(0xFFEDDEE8)
val LightOnSurfaceVariant = Color(0xFF4D444C)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightOutline = Color(0xFF7F747D)

val DarkPrimary = Color(0xFFFFADE1)
val DarkOnPrimary = Color(0xFF5D005D)
val DarkPrimaryContainer = Color(0xFF840084)
val DarkOnPrimaryContainer = Color(0xFFFFD7F3)
val DarkSecondary = Color(0xFFDCBED3)
val DarkOnSecondary = Color(0xFF3E2A3A)
val DarkSecondaryContainer = Color(0xFF564052)
val DarkOnSecondaryContainer = Color(0xFFF9DAEF)
val DarkTertiary = Color(0xFFF6B8AD)
val DarkOnTertiary = Color(0xFF4C251E)
val DarkTertiaryContainer = Color(0xFF673B33)
val DarkOnTertiaryContainer = Color(0xFFFFDAD4)
val DarkBackground = Color(0xFF0D0A0F)
val DarkOnBackground = Color(0xFFE9E0E4)
val DarkSurface = Color(0xFF120F14)
val DarkOnSurface = Color(0xFFE9E0E4)
val DarkSurfaceVariant = Color(0xFF252024)
val DarkOnSurfaceVariant = Color(0xFFD0C3CC)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkOutline = Color(0xFF4D444C)