package io.github.itsmelissadev.swiftsense.ui.theme

import androidx.compose.ui.graphics.Color

// Shadcn UI Style Colors - Light (Zinc)
val LightBackground = Color(0xFFFFFFFF)
val LightForeground = Color(0xFF09090b)
val LightCard = Color(0xFFF9FAFB)
val LightCardForeground = Color(0xFF09090b)
val LightPrimary = Color(0xFF18181b)
val LightOnPrimary = Color(0xFFfafafa)
val LightSecondary = Color(0xFFf4f4f5)
val LightOnSecondary = Color(0xFF18181b)
val LightMuted = Color(0xFFf4f4f5)
val LightOnMuted = Color(0xFF71717a)
val LightAccent = Color(0xFFf4f4f5)
val LightOnAccent = Color(0xFF18181b)
val LightBorder = Color(0xFFe4e4e7)
val LightInput = Color(0xFFe4e4e7)
val LightRing = Color(0xFF18181b)

// Shadcn UI Style Colors - Dark (Zinc)
val DarkBackground = Color(0xFF09090b)
val DarkForeground = Color(0xFFfafafa)
val DarkCard = Color(0xFF0F1117)
val DarkCardForeground = Color(0xFFfafafa)
val DarkPrimary = Color(0xFFfafafa)
val DarkOnPrimary = Color(0xFF18181b)
val DarkSecondary = Color(0xFF27272a)
val DarkOnSecondary = Color(0xFFfafafa)
val DarkMuted = Color(0xFF27272a)
val DarkOnMuted = Color(0xFFa1a1aa)
val DarkAccent = Color(0xFF27272a)
val DarkOnAccent = Color(0xFFfafafa)
val DarkBorder = Color(0xFF27272a)
val DarkInput = Color(0xFF27272a)
val DarkRing = Color(0xFFd4d4d8)

// Extra Semantic Colors
val Error = Color(0xFFef4444)
val Success = Color(0xFF22c55e)
val Warning = Color(0xFFf59e0b)
